[package]
name = "telegram"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
source-downloader-sdk = { path = "../../source-downloader-sdk" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
futures-util = { workspace = true }
grammers-client = { workspace = true }
grammers-session = { workspace = true }
qrcode = { workspace = true }
base64 = { workspace = true }
postcard = { workspace = true }
time = { workspace = true, features = ["local-offset"] }
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
