[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
sdk = { path = "../sdk" }
log = "0.4"
libloading = "0.8"
serde_yaml = "0.9.34"
serde = { version = "1.0.219", features = ["derive"] }
moka = { version = "0.12.10", features = ["sync"] }

[dev-dependencies]
env_logger = "0.11"
tempfile = "3.19"