[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
source-downloader-sdk = { path = "../../source-downloader-sdk" }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
rss-for-mikan = { workspace = true }
time = { workspace = true }
reqwest = { workspace = true, features = ["rustls", "json", "system-proxy", "http2", "charset", "cookies", "form", "query"] }
bytes = { workspace = true }
moka = { workspace = true, features = ["future"] }
scraper = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
anitomy = { workspace = true }
imagesize = { workspace = true }
lingua = { workspace = true }
infer = { workspace = true }
url = { workspace = true }
encoding_rs = { workspace = true }
chardetng = { workspace = true }
quick-xml = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
wiremock = "0.6"
tempfile = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "anime_file_filter"
harness = false

[[bench]]
name = "doujin_title_trimmer"
harness = false

[[bench]]
name = "simple_file_tagger"
harness = false

#[lib]
#crate-type = ["dylib", "rlib"]